### ISSUE TITLE
Add DesignSPHysics to FreeCAD addons/macro repo

### ISSUE THREAD

**Issue by luzpaz** [ndrs92/DesignSPHysics#2]
Any interest in adding DesignSPHysics to https://github.com/FreeCAD/FreeCAD-macros ?

**Comment by ndrs92** [comment]
I saw the repo you linked a while ago, but, even if DesignSPHysics starts as a macro (maybe changed in the future) its purpose is not really related to the ones found in FreeCAD-macros, as it is a full embedded application to use an external software, more than a set of tools to ease modeling or design.

So I don't really think it is appropiate to add it to that repo. Thanks for the notification though.

**Comment by luzpaz** [comment]
I see, maybe consider it as a plugin? https://github.com/FreeCAD/FreeCAD-addons 
Nevertheless, there are some interesting developments happening in [FEM FreeCAD sub-forum](https://forum.freecadweb.org/viewforum.php?f=18) that might beneficially impact your work on DesignSPHysics...?

**Comment by ndrs92** [comment]
I'll include DesignSPHysics into the addons repository once the [Spheric workshop](http://spheric2017.uvigo.es/) is over, as we don't want to make it more public than this for now. 

About the sub-forum, it's good to know that developing is active, and sure, if I have any problem with FreeCAD related stuff i'll definitely check it for help. Thanks!

I'll mark this as solved and I'll add this to the addons repo when the time comes. Thanks for the suggestions :)

**Comment by luzpaz** [comment]
sorry if I'm bugging you, just wondering if it's ready to be added ?

**Comment by ndrs92** [comment]
Hi!

I'm sorry, I forgot about this. It is indeed ready to be added.

Do I need to do something about it? Thanks

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD-addons/issues/21
ping @yorikvanhavre

**Comment by yorikvanhavre** [comment]
Basically your module needs to be either a macro or a workbench. As far as I can see, everything is launched from the DSPH.py script, right? I would then suggest to either rename the DSPH.py script to DSPH.FCMacro, or, maybe better,  to add a new FCMacro file, so it will be picked and automatically installed by the addon manager. 

What will happen is that your whole module folder will stay inside FreeCAD/Mod, and the macro file will be copied to the Macros directory. But your folder will also be added to the Python path, so for ex. inside your macro you'll be able to do "import DSPH". Since the DSPH script will stay where it is, it should also find all its images and additional files.

**Comment by ndrs92** [comment]
Hi @yorikvanhavre !

Thanks for the explanation. Tomorrow I'll adapt the tool to be compatible with the addon manager. Once it's done I'll notify you in FreeCAD/FreeCAD-addons#21

**Comment by ndrs92** [comment]
The code has been adapted and added to the repo. Closing this now
